### PR TITLE
Update Glitch remix link for logged out/anonymous users

### PR DESCRIPTION
**Pull request by blakewenloe**
Github imports don't work with Glitch if the user isn't logged in to Glitch, but "cloning" does. See the issue here for reference: https://support.glitch.com/t/github-imports-silently-fail-when-not-logged-in/1013/4

### Motivation

Fixes #`135`

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

**Comment by cori** [comment]
Hey folks, we over at Glitch are wondering where the original link that @blakewenloe updated came from - it's kind of a hidden, undocumented backend method that has user interface affordances on the front end to make clear that folks need to sign in to use it - we're trying to determine how we should handle not-logged-in users who call that method directly.

@petrsvihlik it looks like you added the Remix on Glitch button a couple of years ago. That's quite a while back, but do you happen to remember where you found that information?

**Comment by blakewenloe** [comment]
@cori I found the remix button generator here https://remix-button.glitch.me/ and it has a link to make a button that imports from Github after the first paragraph: https://github-import.glitch.me/. That generates the old link that you're seeing.

The URL to the remix button generator is posted here https://glitch.com/help/remixbutton/

**Comment by cori** [comment]
Thanks @blakewenloe, I'd forgotten about that project!

**Comment by petrsvihlik** [comment]
@cori yeah, I think I must have used the generator @blakewenloe mentioned.

**Pull request merged**
