### PR TITLE
seo metadata content type snippets

### PR DESCRIPTION
**Pull request by liamgold**
This is related to https://github.com/Kentico/cloud-sample-app-react/issues/55

### CODE REVIEW

**Comment by liamgold** [comment]
Fixed the case sensitivity issues with the rebuilt models!

Please review and let me know if the implementation is wrong, or recommend any changes 👍

**Comment by petrsvihlik** [comment]
it looks good to me -> merged ;) thanks @liamgold !

**Comment by petrsvihlik** [comment]
would you be interested in another JavaScript issue? we can suggest you some that we need help with. e.g. https://github.com/Kentico/cloud-sample-app-vue/issues/1

**Comment by liamgold** [comment]
Sure - I've not used Vue before so might be a nice to investigate.  Especially since the proposed fix is based upon the React solution

**Comment by petrsvihlik** [comment]
awesome! i can assign the issue to you if you accept the invite to the project ;)

**Pull request merged**
