### PR TITLE
Added Contact page

### PR DESCRIPTION
**Pull request by daemoon**
Created Contact page in React. Had to add GoogleMapsAPI which is used for Maps and Markers used there.

### CODE REVIEW

**Comment by petrsvihlik** [comment]
Hi @daemoon , thanks for the PR. It looks fine, I found just a few things that should be fixed before we merge it:

1. The Contact page gives several warnings in the dev console:

> webpack:///(webpack)-dev-server/client?:41 ./src/Pages/Contacts.js
> 
> C:\Users\-\Documents\GitHub\DeliverDancingGoatSPA\src\Pages\Contacts.js
>   63:37  warning  Script URL is a form of eval  no-script-url
>   78:41  warning  Script URL is a form of eval  no-script-url
> 
> ✖ 2 problems (0 errors, 2 warnings)
> 
> warnings @ webpack:///(webpack)-dev-server/client?:41
> webpack:///(webpack)-dev-server/client?:41 ./src/Components/Marker.js
> 
> C:\Users\-\Documents\GitHub\DeliverDancingGoatSPA\src\Components\Marker.js
>    1:8   warning  'React' is defined but never used    no-unused-vars
>   51:28  warning  Expected '===' and instead saw '=='  eqeqeq
> 
> ✖ 2 problems (0 errors, 2 warnings)

2. The map doesn't always work - when I refresh the Contact page (ctrl+f5) it works ok but when I navigate to it from another page (e.g. Articles) the map is zoomed somewhere in the center of Paris :) and the red markers are gone.

3. It would be great if you could make it work the same way it does in the [.NET MVC sample](https://github.com/Kentico/Deliver-Dancing-Goat-.NET-MVC) - meaning it should zoom into an office when you click its address (the red box above the map).

Thanks again!

**Comment by daemoon** [comment]
Hey,
I've done this as part of my job interview so it might be a bit messy as I had no prior experience with React. I'll try to fix this once I'll gain more experience.

**Comment by petrsvihlik** [comment]
@Simply007 Could you please resolve the conflicts, implement the remarks and merge it?

**Comment by Simply007** [comment]
@petrsvihlik - do you want just resolve the conflict, or rewrite contact page to load data using TS SDK?

**Comment by petrsvihlik** [comment]
ideally use the TS SDK + resolve my previous comments

**Comment by Simply007** [comment]
Will be solved in https://github.com/Kentico/cloud-sample-app-react/pull/49

**Pull request closed without merging**
