### PR TITLE
Set up automated formatting

### LINKED ISSUE #84: Add ESLint & unify coding style
There are some inconsistencies in code style, especially in the use of apostrophes vs double quotes.

Example:

```
import { resolveContentLink } from '../Utilities/ContentLinks'
import BrewerStore from "../Stores/Brewer";
```

Suggested approach:
- [ ] fix the ESLint configuration in this [project](https://github.com/Kentico/cloud-sample-app-react/blob/master/package.json)
  - there are some [standard configs](https://github.com/standard/eslint-config-standard-react) available on the web
  - ideally, configure ESLint to fix issues automatically
- [ ] use ESLint to identify issues and fix them

### PR DESCRIPTION
**Pull request by cbeard87**
To avoid ejecting from the create-react-app build tool, the official recommendations for setting up automated code formatting (found [here](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#formatting-code-automatically)) were followed.

- Uses prettier for code formatting

- Uses husky and lint-staged to set up Githook formatting automation

- Adds eslintrc.json to enable in-editor linting

Closes #84

### CODE REVIEW

**Comment by petrsvihlik** [comment]
thanks for the PR, @cbeard87! there was another PR in the queue which I just merged (#94) could you please resolve the conflicts?

**Comment by cbeard87** [comment]
@petrsvihlik After a bit of difficulty resolving the conflicts, I ended up having to perform a reset on my branch to reflect the changes made in #94. From there I was able to reintegrate the autoformatting as before. Let me know if you have any questions.

**Comment by petrsvihlik** [comment]
it looks good to me :) thank you @cbeard87! would you be interested in another JS or other issue? we can suggest you some that we need help with.

**Comment by cbeard87** [comment]
@petrsvihlik Absolutely! Just let me know where I can help out and I'll be more than happy to jump in.

**Comment by petrsvihlik** [comment]
@cbeard87 I guess you're mostly interested in JS projects. You can hae a look at our [priorities](https://github.com/orgs/Kentico/projects/4).

I'd suggest either:
- https://github.com/Kentico/cloud-gatsby/issues/1
- or https://github.com/Kentico/cloud-sample-app-react/issues/81

The second issue says it's blocked by https://github.com/Enngage/kentico-cloud-js/issues/52 but I think the preview URL generation logic can be build as a part of the sample app and extracted as a separate package later on.
The sample implementation for preview link URLs can be seen [in the .NET SDK](https://github.com/Kentico/content-management-sdk-net/pull/9/files).

Please let me know if some of the issues caught your eye. :)

**Pull request merged**
