### PR TITLE
Visitor tracking via custom activities

### PR DESCRIPTION
**Pull request by iamlucie**
According to the Engage team, current tracking does not track visits to single-page applications properly. Tracking can be implemented by when you use custom activities. I've added the tracking code, a sample custom activity call and a tutorial that allows you to try how the tracking works.

### CODE REVIEW

**Comment by Simply007** [comment]
I will make the review.

**Comment by Simply007** [comment]
Review:
@iamlucie 
Please use project guid of the sample application that is stored in Client.js (975bf280-fd91-488c-994c-2f04416e5ee3) to be consistent with the deliver API.

I would be awesome to extract sample logging calls to separate module from Header.js. Ideally does not log anything until user does not set the code name of the activity for the users who does want to just install sample and take a look how does it look like without activity feature.

Testing:
Works as expected.

**Comment by iamlucie** [comment]
@Simply007 Thanks for the review. Don't you know whether there's some best practice in React or JS in general to separate the logging calls?

**Comment by iamlucie** [comment]
To see changes, check the first and the last commit. The other two are there because I was confused whether I am pulling the updates to this fork or not.

**Comment by Simply007** [comment]
As we have discussed, we want to prepare the sample app to not track any activity after the user just download, just prepare an "architecture".
After a user will connect the app with its own sample app we want to provide a tutorial how to enable logging activity.

TODO:
* Set parameter from function call in header.js to empty string
* Set activity codename parameter from ActivityLogging.js to empty string
* Reflect changes in in README.md
** Just one note for step 5 - ket('start', ''); is not a function it is a function call :-)

Thank for the pull :+1:

**Comment by iamlucie** [comment]
A note for myself based on our discussion: Also make the function name more specific, LogAboutUs or similar.

**Pull request merged**
