### PR TITLE
Footer Component

### PR DESCRIPTION
**Pull request by jmb521**
I attempted to complete the language changes, however I was unsuccessful.

### CODE REVIEW

**Comment by Simply007** [comment]
@jmb521 Thank you! This is exactly what we wanted.

I went through the the changes and everything looks fine.

According to multilingual support:
You can get inspired by i.e. translation of OurStory component:
https://github.com/Kentico/cloud-sample-app-react/commit/d102d009ff284b8a6b84e34ac2015a6100fc3721

1. It is necessary to add translation to local files with appropriate codenames:
i.e.:
```
{
...
"Footer" :    {
    "codename" : "Some translation we want to add to the footer"
    }    
}
```
 - src/Localization/en-US.json
 - src/Localization/es-ES.json
2. Encapsulate component to the HOC on src/Components/Footer.js: 
```
import { translate } from 'react-translate'
...
const Footer = (props) => {
...
}
export default translate("OurStory")(OurStory); 
```
3. use ```{props.t("codename")}``` to get the content in the localization json 

Hint:
You can use parameters in resource strings: 
https://www.npmjs.com/package/react-translate

Some more info:
Application loads all json files in folder /src/Localization https://github.com/Kentico/cloud-sample-app-react/blob/master/src/Utilities/LocalizationLoader.js and stores them as an initial object for ```TranslatorProvider``` https://github.com/Kentico/cloud-sample-app-react/blob/master/src/LocalizedApp.js#L46 from package https://www.npmjs.com/package/react-translate.

**Comment by jmb521** [comment]
I made the changes. Not sure what I need to do now, if anything.

**Comment by Simply007** [comment]
Fixes #65

**Comment by Simply007** [comment]
Thank you, it is awesome to get as precise pull request 👍 

Everything you have dome is exactly, what was required in this task.

Thank you very much.

If you are looking for another issue to grab, it would be the best to remove two unnecessary fields in the Article model (/Models/Article)  described in issue comment:
https://github.com/Kentico/cloud-sample-app-react/issues/55#issuecomment-351025455

We have also defined a content snippet in the brewer content type (first part of the issue) (https://deliver.kenticocloud.com/975bf280-fd91-488c-994c-2f04416e5ee3/items/aeropress) but we need to decide, how do we want do use them on the sample app. It will be probably something similar as in our .net sample app https://github.com/Kentico/cloud-sample-app-net.

So if you are interested, just let me know and i will prepare the description.

Thanks again :-)

**Pull request merged**
